# Generated by Django 4.1.1 on 2022-11-11 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id_cart', models.AutoField(primary_key=True, serialize=False)),
                ('price_cart', models.FloatField()),
                ('nbr_produitCart', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_categorie', models.AutoField(primary_key=True, serialize=False)),
                ('titre_category', models.CharField(max_length=400)),
                ('nbr_prodcate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('img', models.ImageField(upload_to='')),
                ('id_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('num_telephone', models.CharField(max_length=14)),
                ('username', models.CharField(max_length=30)),
                ('password', models.TextField(max_length=30)),
                ('id_cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id_achat', models.AutoField(primary_key=True, serialize=False)),
                ('date_achat', models.DateField()),
                ('id_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categorie')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produit')),
            ],
        ),
    ]
