# Generated by Django 4.1.1 on 2022-11-20 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='produit',
            table='app_produit',
        ),
    ]
