# # Generated by Django 4.1.1 on 2022-11-25 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_produit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='id_categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categorie'),
        ),
    ]
