# # Generated by Django 4.1.1 on 2022-11-30 20:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_produit_id_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id_book', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('img', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id_commande', models.AutoField(primary_key=True, serialize=False)),
                ('Commande_price', models.FloatField()),
                ('nbr_produit', models.IntegerField()),
                ('price_commande', models.FloatField()),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id_ligne', models.AutoField(primary_key=True, serialize=False)),
                ('product_quantity', models.IntegerField()),
                ('price_discount', models.FloatField()),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.book')),
            ],
        ),
        migrations.CreateModel(
            name='Paiment',
            fields=[
                ('id_paiment', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=14)),
                ('username', models.CharField(max_length=30)),
                ('password', models.TextField(max_length=30)),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='produit',
            name='id_categorie',
        ),
        migrations.RenameField(
            model_name='categorie',
            old_name='nbr_prodcate',
            new_name='nbr_book',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='password',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='username',
        ),
        migrations.RemoveField(
            model_name='client',
            name='id_cart',
        ),
        migrations.RemoveField(
            model_name='client',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='client',
            name='num_telephone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
        migrations.RemoveField(
            model_name='client',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='client',
            name='username',
        ),
        migrations.AddField(
            model_name='admin',
            name='created_at',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='admin',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorie',
            name='created_at',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Achat',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Produit',
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='id_categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categorie'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='id_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
        migrations.AddField(
            model_name='commande',
            name='id_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client'),
        ),
        migrations.AddField(
            model_name='commande',
            name='id_paiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.paiment'),
        ),
        migrations.AddField(
            model_name='commande',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
        migrations.AddField(
            model_name='book',
            name='id_categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categorie'),
        ),
        migrations.AddField(
            model_name='admin',
            name='user_id',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
        migrations.AddField(
            model_name='client',
            name='user_id',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
