# # Generated by Django 4.1.1 on 2022-11-30 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_book_commande_lignecommande_paiment_user_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table='Admin',
        ),
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
        migrations.AlterModelTable(
            name='categorie',
            table='Categorie',
        ),
        migrations.AlterModelTable(
            name='client',
            table='Client',
        ),
        migrations.AlterModelTable(
            name='commande',
            table='Commande',
        ),
        migrations.AlterModelTable(
            name='lignecommande',
            table='LigneCommande',
        ),
        migrations.AlterModelTable(
            name='paiment',
            table='Paiment',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
