# # Generated by Django 4.1.1 on 2022-11-30 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_admin_user_id_alter_client_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='user_id',
            new_name='id_user',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='user_id',
        ),
        migrations.AddField(
            model_name='admin',
            name='id_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.user'),
            preserve_default=False,
        ),
    ]
