# # Generated by Django 4.1.1 on 2022-11-30 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_user_id_client_id_user_remove_admin_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
