# # Generated by Django 4.1.1 on 2022-11-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_client_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='surname',
            field=models.CharField(default='med', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='niv_fidélité',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
