# # Generated by Django 4.1.1 on 2022-11-30 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_admin_user_remove_client_user_admin_id_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='id_user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='id_user',
            new_name='user_id',
        ),
    ]
