# Generated by Django 4.1.1 on 2022-12-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_id_user_admin_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='client',
            name='niv_fidélité',
        ),
        migrations.RemoveField(
            model_name='client',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='lignecommande',
            name='id_user',
        ),
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.CharField(default='mohamedabi@gmail.com', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.TextField(default='medmedmed', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='phone',
            field=models.CharField(default='037737728', max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='username',
            field=models.CharField(default='med07', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(default='mohamedabi09@gmail.com', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='nom',
            field=models.CharField(default='abi', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.TextField(default='med09', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(default='038726782', max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='prenom',
            field=models.CharField(default='mohamed', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.CharField(default='moha09', max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
